### PR TITLE
Fix code Format

### PR DESCRIPTION
**Pull request by eduardobaitello**

### CODE REVIEW

**Review by thaJeztah — APPROVED** [review]
LGTM

**Comment by thaJeztah** [comment]
oh, can you sign-off and amend your commit? https://github.com/docker/go-healthcheck/blob/master/CONTRIBUTING.md#sign-your-work

**Comment by eduardobaitello** [comment]
@thaJeztah I signed it

**Review by vdemeester — APPROVED** [review]
LGTM 🐮

**Comment by thaJeztah** [comment]
Thanks!

**Pull request merged**
